format = """
$username\
$directory\
$git_branch\
$git_status\
$haskell\
$lua\
$python\
$java\
$php\
$nodejs\
$rust\
$cmd_duration
$time[» ](bold green)
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#ccb7f2"
style_root = "fg:#ccb7f2"
# format = '[ $user@linux:  ]($style)'
format = '[  ]($style)'

[directory]
style = "fg:#96cdfb"
format = "[ in ](fg:#988ba2)[$path ]($style bold)"
truncation_length = 8 
truncate_to_repo = true
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = 'שׂ '
style = "fg:#ddb6f2"
format = '[[on](fg:#988ba2) $symbol$branch](bold $style)'

[git_status]
style = "fg:#f38ba8"
format = '[($all_status$ahead_behind)]($style)'

[haskell]
symbol = " "
style = "fg:#abe9b3"
format = '[[ via ](fg:#988ba2)$symbol($version) ](bold $style)'

[lua]
symbol = " "
style = "fg:#abe9b3"
format = '[[ via ](fg:#988ba2)$symbol($version) ](bold $style)'

[python]
symbol = " "
style = "fg:#abe9b3"
format = '[[ via ](fg:#988ba2)$symbol($version) ](bold $style)'

[java]
symbol = " "
style = "fg:#abe9b3"
format = '[[ via ](fg:#988ba2)$symbol($version) ](bold $style)'

[php]
symbol = "  "
style = "fg:#abe9b3"
format = '[[ via ](fg:#988ba2)$symbol($version) ](bold $style)'

[nodejs]
symbol = " "
style = "fg:#abe9b3"
format = '[[ via ](fg:#988ba2)$symbol($version) ](bold $style)'

[rust]
symbol = " "
style = "fg:#abe9b3"
format = '[[ via ](fg:#988ba2)$symbol($version) ](bold $style)'

[cmd_duration]
format = '[ took ](fg:#988ba2)[$duration]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = ""
format = '[[ ⚡](fg:#fae3b0)$time ]($style)'
