require "dt.options"
require "dt.keymaps"
require "dt.plugins"
require "dt.barbar" -- Integrated into solarized theme config file
-- require "dt.bufferline"
-- themes ---------------------------------------------------------------------
-- require "dt.themes.rose"
-- require "dt.themes.monokai"
-- require "dt.lines.onedark"
-- require "dt.themes.onedark"
-- require "dt.lines.onedark"
require "dt.themes.solarized"
require "dt.lines.solarized"
-- require "dt.themes.cat"
-- require "dt.lines.cat"
-- require "dt.themes.gruv"
-- require "dt.lines.gruv"
-------------------------------------------------------------------------------
require "dt.telescope"
require "dt.cmp"
require "dt.lsp"
require "dt.treesitter"
require "dt.autopairs"
require "dt.comment"
require "dt.nvim-tree"
require "dt.gitsigns"
require "dt.toggleterm"
require "dt.alpha"
require "dt.impatient"
require "dt.hop"
require "dt.null-ls"
require "dt.coloraizer"
require "dt.scroll"
